"""Merge the card list (cards.json), film metadata (films.txt) and resolved
iTunes previews (previews.json) into ../songs.js."""
import json, os

here = os.path.dirname(os.path.abspath(__file__))
cards = json.load(open(os.path.join(here, 'cards.json'), encoding='utf-8'))
films = [l.rstrip('\n').split('|') for l in open(os.path.join(here, 'films.txt'), encoding='utf-8') if l.strip()]
previews = json.load(open(os.path.join(here, 'previews.json'), encoding='utf-8'))
assert len(cards) == len(films), (len(cards), len(films))

songs = []
for i, (c, f) in enumerate(zip(cards, films)):
    film, orig, year, kind, composer = f
    p = previews.get(str(i)) or {}
    art = p.get('art')
    songs.append({
        'id': i + 1,
        'film': film,
        'orig': orig,
        'year': int(year),
        'kind': kind,
        'composer': composer,
        'artist': c['artist'],
        'title': c['title'],
        'cardYear': int(c['year']),
        'preview': p.get('preview', ''),
        'trackId': p.get('trackId'),
        'art': art.replace('100x100bb', '300x300bb') if art else '',
    })

with open(os.path.join(here, '..', 'songs.js'), 'w', encoding='utf-8') as out:
    out.write('// Generated by tools/build_songs.py – do not edit by hand.\n')
    out.write('window.SONGS = ')
    json.dump(songs, out, ensure_ascii=False, indent=1)
    out.write(';\n')
print(len(songs), 'songs,', sum(1 for s in songs if s['preview']), 'with preview')
