"""Build ../songs.js from the card list and metadata in this folder.

cards.csv    official card data of the German "Movies & TV Soundtracks" edition
             (from github.com/andygruber/songseeker-hitster-playlists, MIT)
films.txt    one line per card: Film (DE) | original title | year | F/S | composer
spotify.json Spotify track per card (same order as cards.csv)
"""
import csv, json, os, re

here = os.path.dirname(os.path.abspath(__file__))
cards = list(csv.DictReader(open(os.path.join(here, 'cards.csv'), encoding='utf-8')))
films = [l.rstrip('\n').split('|') for l in open(os.path.join(here, 'films.txt'), encoding='utf-8') if l.strip()]
spotify = json.load(open(os.path.join(here, 'spotify.json'), encoding='utf-8'))
assert len(cards) == len(films) == len(spotify), (len(cards), len(films), len(spotify))

# Obvious typos in the source data.
FIXES = {'Marry Poppins': 'Mary Poppins', 'Also Spracht': 'Also sprach', 'Dominik Hause ': 'Dominik Hauser ',
         'Das Phantom der Opera': 'Das Phantom der Oper', 'Der Rosarote Panther': 'Der rosarote Panther'}

def fix(s):
    for a, b in FIXES.items():
        s = s.replace(a, b)
    return s.strip()

def clean_track(t):
    return re.split(r' - (?:From|from|Theme from|Main Title|Remaster|\d{4} Remaster|Instrumental|Soundtrack|Studio|Single|End Title|Concert)| \((?:From|from|Original)', t)[0].strip()

songs = []
for i, (c, f, sp) in enumerate(zip(cards, films, spotify)):
    title = fix(c['Title'])
    m = re.match(r'^(.*?) \((.*)\)$', title)
    film_on_card, song = (m.group(1), m.group(2)) if m else (title, '')
    _, orig, _, kind, composer = f
    artist = fix(c['Artist']).replace(',', ', ').replace('  ', ' ')
    songs.append({
        'id': int(c['Card#']),
        'film': film_on_card,
        'orig': orig if orig and orig.lower() not in film_on_card.lower() else '',
        'year': int(c['Year']),
        'kind': kind,
        'artist': artist,
        'composer': composer if composer and composer.lower() not in artist.lower() else '',
        'title': song or clean_track(sp['title']),
        'spotify': sp['id'],
        'cover': sp['cover'],
        'youtube': c['URL'],
    })

with open(os.path.join(here, '..', 'songs.js'), 'w', encoding='utf-8') as out:
    out.write('// Generated by tools/build_songs.py – do not edit by hand.\n')
    out.write('window.SONGS = ')
    json.dump(songs, out, ensure_ascii=False, indent=1)
    out.write(';\n')
print(len(songs), 'songs')
